### PR TITLE
Adds param? method to main cuba.rb file for optional param matching. This allows you do still capture (vs doing req.params[somekey] an optional querystring param.

### PR DESCRIPTION
**Pull request by jaydanielian**

### CODE REVIEW

**Comment by soveran** [comment]
@mkristian I'm not sure about extending the API with this method. I understand its merits, especially with the default value. What it makes me wonder is if in the future we can consider adding a second parameter to `param` as part of the API. I think the end result would be applicable to your use case.

**Comment by mkristian** [comment]
@soveran after reading this again, I do see my point again. if the default applies whenever the parameter is missing, then it is a catch always construct: either catch it since the parameter is present or catch it and use the default. I did not read the code so my interpretation might be wrong.

**Comment by soveran** [comment]
@mkristian I explained myself badly, sorry :-) I thought you were asking if, by adding the default, it would become a predicate that always matches. I think the proposed `param?` method always matches, even without the default value. Then I commented on the fact that a default value could be incorporated into the current `param` method, and it would be `nil` if not provided. That way, for the normal use case the behavior will remain the same (because of that `nil`), but if a default value is provided it becomes a catch always construct, as you said.

@jaydanielian What do you think about that idea?

**Comment by jaydanielian** [comment]
@soveran - that certainly seems to work. My main wish was having a way to have an optional parameter (with potential default value) that I could easily "see" when defining the route, which if I understand what you are proposing, would do the trick.

**Comment by soveran** [comment]
@jaydanielian The second parameter for the default value has been added as an experimental feature to 3.5.0. Thanks a lot for your input!

**Comment by jaydanielian** [comment]
@soveran No problem, thanks for this project! We have been using it in production for over a year now and it has been fantastic. We use it for our REST API using torquebox server / jRuby and have been very pleased with the performance. Great work!

**Comment by soveran** [comment]
@jaydanielian Glad to hear that! Feel free to ask me for help with anything, I'm really glad this tools is useful for you :-)

**Pull request closed without merging**
